In [2]:
from tensorflow.keras.preprocessing.text import one_hot

I0000 00:00:1779093262.907865    9525 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1779093263.961822    9525 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1779093267.646002    9525 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.


In [3]:
## Sentence
sent = [
  'the glass of milk',
  'the glass of juice',
  'the cup of tea',
  'I am a good boy',
  'I am a good developer',
  'understand the meaning of words',
  'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the voccabulary size
voc_size =  10000

In [6]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[3188, 2237, 5902, 5310],
 [3188, 2237, 5902, 3536],
 [3188, 6095, 5902, 1217],
 [5887, 4215, 3986, 8236, 600],
 [5887, 4215, 3986, 8236, 946],
 [1153, 3188, 2256, 5902, 590],
 [2525, 5644, 8354, 8236]]

In [27]:
## Word embedding representation
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [18]:
import numpy as np

In [19]:
sent_length = 10
embedded_doc = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

print(embedded_doc)

[[   0    0    0    0    0    0 3188 2237 5902 5310]
 [   0    0    0    0    0    0 3188 2237 5902 3536]
 [   0    0    0    0    0    0 3188 6095 5902 1217]
 [   0    0    0    0    0 5887 4215 3986 8236  600]
 [   0    0    0    0    0 5887 4215 3986 8236  946]
 [   0    0    0    0    0 1153 3188 2256 5902  590]
 [   0    0    0    0    0    0 2525 5644 8354 8236]]


In [ ]:
## Feature representation

dim = 10

In [26]:
model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(input_dim=voc_size, output_dim=dim)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step


array([[[-0.04527977, -0.00645746, -0.0081107 ,  0.04959022,
          0.03504062, -0.00318683,  0.02470173, -0.04326219,
         -0.0055514 , -0.00820692],
        [-0.04527977, -0.00645746, -0.0081107 ,  0.04959022,
          0.03504062, -0.00318683,  0.02470173, -0.04326219,
         -0.0055514 , -0.00820692],
        [-0.04527977, -0.00645746, -0.0081107 ,  0.04959022,
          0.03504062, -0.00318683,  0.02470173, -0.04326219,
         -0.0055514 , -0.00820692],
        [-0.04527977, -0.00645746, -0.0081107 ,  0.04959022,
          0.03504062, -0.00318683,  0.02470173, -0.04326219,
         -0.0055514 , -0.00820692],
        [-0.04527977, -0.00645746, -0.0081107 ,  0.04959022,
          0.03504062, -0.00318683,  0.02470173, -0.04326219,
         -0.0055514 , -0.00820692],
        [-0.04527977, -0.00645746, -0.0081107 ,  0.04959022,
          0.03504062, -0.00318683,  0.02470173, -0.04326219,
         -0.0055514 , -0.00820692],
        [ 0.00125857,  0.02187966, -0.01912066, -0.0